#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudAwesome.Xrm.Simulate.Test.EarlyBoundEntities
{
	
	
	/// <summary>
	/// Drop-down list for selecting the category of the account.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_AccountCategoryCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PreferredCustomer = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Standard = 2,
	}
	
	/// <summary>
	/// Drop-down list for classifying an account.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_AccountClassificationCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Drop-down list for selecting account ratings.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_AccountRatingCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Type of address for address 1, such as billing, shipping, or primary address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_Address1_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BillTo = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Primary = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ShipTo = 2,
	}
	
	/// <summary>
	/// Freight terms for address 1.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_Address1_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fob = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoCharge = 2,
	}
	
	/// <summary>
	/// Method of shipment for address 1.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_Address1_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Airborne = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dhl = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fedex = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FullLoad = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostalMail = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ups = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WillCall = 7,
	}
	
	/// <summary>
	/// Type of address for address 2, such as billing, shipping, or primary address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_Address2_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Freight terms for address 2.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_Address2_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Method of shipment for address 2.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_Address2_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Type of business associated with the account.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_BusinessTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Size of the account.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_CustomerSizeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Type of the account.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_CustomerTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Competitor = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consultant = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customer = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Influencer = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Investor = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Partner = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Press = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Prospect = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reseller = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Supplier = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Vendor = 11,
	}
	
	/// <summary>
	/// Type of industry with which the account is associated.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_IndustryCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Accounting = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgricultureAndNonPetrolNaturalResourceExtraction = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BroadcastingPrintingAndPublishing = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Brokers = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BuildingSupplyRetail = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessServices = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consulting = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConsumerServices = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DesignDirectionAndCreativeManagement = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DistributorsDispatchersAndProcessors = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DoctorSOfficesAndClinics = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DurableManufacturing = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EatingAndDrinkingPlaces = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntertainmentRetail = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EquipmentRentalAndLeasing = 15,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Financial = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FoodAndTobaccoProcessing = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InboundCapitalIntensiveProcessing = 18,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InboundRepairAndServices = 19,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Insurance = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LegalServices = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonDurableMerchandiseRetail = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutboundConsumerService = 23,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PetrochemicalExtractionAndDistribution = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceRetail = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SigAffiliations = 26,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SocialServices = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SpecialOutboundTradeContractors = 28,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SpecialtyRealty = 29,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transportation = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UtilityCreationAndDistribution = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		VehicleRetail = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Wholesale = 33,
	}
	
	/// <summary>
	/// Type of company ownership, such as public or private.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_OwnershipCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Private = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Public = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Subsidiary = 3,
	}
	
	/// <summary>
	/// Payment terms for the account.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_PaymentTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_210Net30 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net30 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net45 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net60 = 4,
	}
	
	/// <summary>
	/// Day of the week that the account prefers for scheduling service activities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_PreferredAppointmentDayCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Friday = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Monday = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Saturday = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sunday = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Thursday = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Tuesday = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Wednesday = 3,
	}
	
	/// <summary>
	/// Time of day that the account prefers for scheduling service activities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_PreferredAppointmentTimeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Afternoon = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Evening = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Morning = 1,
	}
	
	/// <summary>
	/// Preferred contact method for the account.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_PreferredContactMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Any = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fax = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mail = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Phone = 3,
	}
	
	/// <summary>
	/// Method of shipment for the account.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Status of the account.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the account.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Territory to which the account belongs.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Account_TerritoryCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AWe_Benefits
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HousingCredit = 124210000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PensionCreditSavingsElement = 124210002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UniversalCredit = 124210001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AWe_DoYouWantToAddExtraInformation
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		No = 124210000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yes = 124210001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AWe_FloorArea
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_3050Meters = 124210000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_5170Meters = 124210001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_7180Meters = 124210002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_81100Meters = 124210003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Over100Meters = 124210004,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AWe_OrganisationType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CentralGovernment = 124210002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HealthCare = 124210001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LocalAuthority = 124210000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SponsoredBody = 124210003,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AWe_PropertyAge
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_1900OrEarlier = 124210000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_19011920 = 124210001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_19211950 = 124210002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_19511970 = 124210003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_19711999 = 124210004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_20002010 = 124210005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2011OrLater = 124210006,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AWe_PropertyType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DetachedHouse = 124210002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FlatInHighRiseBlock = 124210004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SemiDetachedHouse = 124210003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TenementFlat = 124210001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TerracedHouse = 124210000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AWe_YesNo
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		No = 124210000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yes = 124210001,
	}
	
	/// <summary>
	/// Do they have a budget?
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BudgetStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CanBuy = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MayBuy = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoCommittedBudget = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WillBuy = 3,
	}
	
	/// <summary>
	/// Type of address for address 1, such as billing, shipping, or primary address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BusinessUnit_Address1_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Method of shipment for address 1.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BusinessUnit_Address1_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Type of address for address 2, such as billing, shipping, or primary address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BusinessUnit_Address2_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Method of shipment for address 2.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BusinessUnit_Address2_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// The state of this component.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ComponentState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deleted = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeletedUnpublished = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Published = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unpublished = 1,
	}
	
	/// <summary>
	/// Account role of the contact.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_AccountRoleCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DecisionMaker = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Employee = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Influencer = 3,
	}
	
	/// <summary>
	/// Type of address for address 1, such as billing, shipping, or primary address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address1_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BillTo = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Home = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ShipTo = 2,
	}
	
	/// <summary>
	/// Freight terms for address 1.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address1_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fob = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoCharge = 2,
	}
	
	/// <summary>
	/// Method of shipment for address 1.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address1_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Airborne = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dhl = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fedex = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FullLoad = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostalMail = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ups = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WillCall = 7,
	}
	
	/// <summary>
	/// Type of address for address 2, such as billing, shipping, or primary address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address2_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Freight terms for address 2.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address2_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Method of shipment for address 2.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address2_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Type of address for address 3, such as billing, shipping, or primary address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address3_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Freight terms for address 3.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address3_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Method of shipment for address 3.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Address3_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Size of the contact's business.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_CustomerSizeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Type of business associated with the contact.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_CustomerTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Formal education level that the contact has attained.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_EducationCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Marital status of the contact.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_FamilyStatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Divorced = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Married = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Single = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Widowed = 4,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_FCo_BaggageGuidanceStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReadingComplete = 805500000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_FCo_CarloAnGuidanceStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReadingComplete = 805500000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_FCo_ContinuityOfEducationGuidanceStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReadingComplete = 805500000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_FCo_FinancialGuidanceStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 805500000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_FCo_HeadOfMission
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		No = 805500001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yes = 805500000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_FCo_HowWillYouSendYourBaggage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IWillCarryMyItemsAsExcessBaggage = 805500001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ViaUnaccompaniedAirFreight = 805500000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_FCo_LanguageTrainingStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotApplicable = 805500000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReadingComplete = 805500001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_FCo_ShippingVehicleGuidanceStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReadingComplete = 805500000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_FCo_VisaGuidanceStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReadingComplete = 805500000,
	}
	
	/// <summary>
	/// Gender of the contact.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_GenderCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Female = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Male = 1,
	}
	
	/// <summary>
	/// Information about whether the contact has children.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_HasChildrenCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Source of the lead of the contact.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_LeadSourceCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Indicate buying influence using label
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Msdyn_DecisionInfluenceTag
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Blocker = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DecisionMaker = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Influencer = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unknown = 3,
	}
	
	/// <summary>
	/// For Internal Use only
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_Msdyn_OrgChangeStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ignore = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoFeedback = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotAtCompany = 1,
	}
	
	/// <summary>
	/// Payment terms for the contact.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_PaymentTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_210Net30 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net30 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net45 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net60 = 4,
	}
	
	/// <summary>
	/// Day of the week that the contact prefers for scheduling service activities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_PreferredAppointmentDayCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Friday = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Monday = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Saturday = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sunday = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Thursday = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Tuesday = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Wednesday = 3,
	}
	
	/// <summary>
	/// Time of day that the contact prefers for scheduling service activities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_PreferredAppointmentTimeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Afternoon = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Evening = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Morning = 1,
	}
	
	/// <summary>
	/// Preferred contact method for the contact.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_PreferredContactMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Any = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fax = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mail = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Phone = 3,
	}
	
	/// <summary>
	/// Method of shipping for the contact.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Status of the contact.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the contact.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Unique identifier of the territory to which the contact is assigned.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Contact_TerritoryCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum FCo_CreatedByProcess
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AutomatedTesting = 805500000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataImport = 805500001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ManualByUser = 805500002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemWorkflow = 805500003,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum FCo_ParentDepartment
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fco = 805500000,
	}
	
	/// <summary>
	/// Type of the Contact
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum FCo_TypeOfPerson
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Child = 805500002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SpousePartner = 805500001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TheOverallApplicant = 805500000,
	}
	
	/// <summary>
	/// If there has been initial communication with this lead.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum InitialCommunication
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contacted = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotContacted = 1,
	}
	
	/// <summary>
	/// Type of address for address 1, such as billing, shipping, or primary address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_Address1_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Method of shipment for address 1.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_Address1_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Type of address for address 2, such as billing, shipping, or primary address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_Address2_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Method of shipment for address 2.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_Address2_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Type of industry with which the company or organization of the lead is associated.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_IndustryCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Accounting = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgricultureAndNonPetrolNaturalResourceExtraction = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BroadcastingPrintingAndPublishing = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Brokers = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BuildingSupplyRetail = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BusinessServices = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consulting = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConsumerServices = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DesignDirectionAndCreativeManagement = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DistributorsDispatchersAndProcessors = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DoctorSOfficesAndClinics = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DurableManufacturing = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EatingAndDrinkingPlaces = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntertainmentRetail = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EquipmentRentalAndLeasing = 15,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Financial = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FoodAndTobaccoProcessing = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InboundCapitalIntensiveProcessing = 18,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InboundRepairAndServices = 19,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Insurance = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LegalServices = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonDurableMerchandiseRetail = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutboundConsumerService = 23,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PetrochemicalExtractionAndDistribution = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceRetail = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SigAffiliations = 26,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SocialServices = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SpecialOutboundTradeContractors = 28,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SpecialtyRealty = 29,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transportation = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UtilityCreationAndDistribution = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		VehicleRetail = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Wholesale = 33,
	}
	
	/// <summary>
	/// Quality of the lead, such as hot, warm, or cold.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_LeadQualityCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cold = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Hot = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Warm = 2,
	}
	
	/// <summary>
	/// Source of the lead.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_LeadSourceCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Advertisement = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmployeeReferral = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ExternalReferral = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Partner = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PublicRelations = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Seminar = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TradeShow = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Web = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WordOfMouth = 9,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_Msdyn_SalesAssignmentResult
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Succeeded = 0,
	}
	
	/// <summary>
	/// Preferred contact method for the lead.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_PreferredContactMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Any = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fax = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mail = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Phone = 3,
	}
	
	/// <summary>
	/// Priority of the lead.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_PriorityCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// The sales process stage that this entity is in.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_SalesStage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualify = 0,
	}
	
	/// <summary>
	/// Current stage of the sales process for the lead.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_SalesStageCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Status of the lead.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disqualified = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Open = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualified = 1,
	}
	
	/// <summary>
	/// Reason for the status of the lead.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Lead_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CannotContact = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contacted = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lost = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		New = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoLongerInterested = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualified = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_LeadGradeOptSet
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GradeA = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GradeB = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GradeC = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GradeD = 3,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_LeadScoreTrendOptSet
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Declining = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Improving = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotEnoughInfo = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Steady = 1,
	}
	
	/// <summary>
	/// Need type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Need
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GoodToHave = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MustHave = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoNeed = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ShouldHave = 1,
	}
	
	/// <summary>
	/// Application Based Access Control Mode. 0 is Disabled, 1 is Enabled, 2 is audit mode, 3 is Enabled for roles
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_ApplicationBasedAccessControlMode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Auditmode = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disabled = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enabled = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EnabledForRoles = 3,
	}
	
	/// <summary>
	/// Indication of whether to display money fields with currency code or currency symbol.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_CurrencyDisplayOption
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CurrencyCode = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CurrencySymbol = 0,
	}
	
	/// <summary>
	/// Information about how currency symbols are placed throughout Microsoft CRM.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_CurrencyFormatCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_123_0 = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_123_1 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_123_2 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_123_3 = 3,
	}
	
	/// <summary>
	/// Specifies the default end recurrence range to be used in recurrence dialog.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_DefaultRecurrenceEndRangeType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EndByDate = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoEndDate = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NumberOfOccurrences = 2,
	}
	
	/// <summary>
	/// The status of activation of the Power Automate Desktop Flow Run Action logs.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_DesktopFlowRunActionLogsStatus
	{
		
		/// <summary>
		/// Power Automate Desktop Flow Run Action Logs are disabled.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disabled = 2,
		
		/// <summary>
		/// Power Automate Desktop Flow Run Action Logs are enabled.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enabled = 0,
		
		/// <summary>
		/// Power Automate Desktop Flow Run Action Logs are saved only on failure.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Onfailure = 1,
	}
	
	/// <summary>
	/// Where the Power Automate Desktop Flow Run Action logs are stored.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_DesktopFlowRunActionLogVersion
	{
		
		/// <summary>
		/// Power Automate Desktop Flow Run Action Logs are stored in the Additional Context field of the Flow Session.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Additionalcontext = 0,
		
		/// <summary>
		/// Power Automate Desktop Flow Run Action Logs are stored in the Additional Context field of the Flow Session and the Flow Logs Dataverse Entity (Preview).
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Additionalcontextandflowlogs = 2,
		
		/// <summary>
		/// Power Automate Desktop Flow Run Action Logs are stored in the Flow Logs Dataverse Entity (Preview).
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Flowlogs = 1,
	}
	
	/// <summary>
	/// Discount calculation Method for the QOOI product
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_DiscountCalculationMethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LineItem = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PerUnit = 1,
	}
	
	/// <summary>
	/// Select whether you want to use the Email Router or server-side synchronization for email processing.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_EmailConnectionChannel
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftDynamics365EmailRouter = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServerSideSynchronization = 0,
	}
	
	/// <summary>
	/// Fiscal Period Format
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_FiscalPeriodFormatPeriod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		M0 = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Month0 = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MonthName = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		P0 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Q0 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quarter0 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Semester0 = 6,
	}
	
	/// <summary>
	/// Fiscal Year Format Prefix
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_FiscalYearFormatPrefix
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_2 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fy = 1,
	}
	
	/// <summary>
	/// Fiscal Year Format Suffix
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_FiscalYearFormatSuffix
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_3 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FiscalYear = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fy = 1,
	}
	
	/// <summary>
	/// Fiscal Year Format
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_FiscalYearFormatYear
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ggyy = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yy = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yyyy = 1,
	}
	
	/// <summary>
	/// Order in which names are to be displayed throughout Microsoft CRM.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_FullNameConventionCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FirstName = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FirstNameMiddleInitialLastName = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FirstNameMiddleNameLastName = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LastNameFirstName = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LastNameFirstNameMiddleInitial = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LastNameFirstNameMiddleName = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LastNameNoSpaceFirstName = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LastNameSpaceFirstName = 6,
	}
	
	/// <summary>
	/// Select which IP Based SAS URI restriction will be used.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_IpBasedStorageAccessSignatureMode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IpBindingAndIpFirewall = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IpBindingOnly = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IpBindingOrIpFirewall = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IpFirewallOnly = 1,
	}
	
	/// <summary>
	/// Flag that determines whether or not MSCRM should be loaded in an browser window that does not have address, tool and menu bars.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_IsvIntegrationCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		All = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Outlook = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutlookLaptopClient = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutlookWorkstationClient = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Web = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebOutlookLaptopClient = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebOutlookWorkstationClient = 3,
	}
	
	/// <summary>
	/// Show legacy app for admins
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_LegacyAppToggle
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Auto = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Off = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		On = 1,
	}
	
	/// <summary>
	/// Information that specifies how negative numbers are displayed throughout Microsoft CRM.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_NegativeFormatCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Brackets = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dash = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DashPlusSpace = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SpacePlusTrailingDash = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TrailingDash = 3,
	}
	
	/// <summary>
	/// Organization State, indicates if the org is being created, upgraded, updated or active
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_OrganizationState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Creating = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Updating = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Upgrading = 1,
	}
	
	/// <summary>
	/// Plug-in Trace Log Setting for the Organization.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_PluginTraceLogSetting
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		All = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Exception = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Off = 0,
	}
	
	/// <summary>
	/// Model app refresh channel
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_ReleaseChannel
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Auto = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftInnerChannel = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MonthlyChannel = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SemiAnnualChannel = 3,
	}
	
	/// <summary>
	/// Picklist for selecting the user preference for reporting scripting errors.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_ReportScripTerrors
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AskMeForPermissionToSendAnErrorReportToMicrosoft = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AutomaticallySendAnErrorReportToMicrosoftWithoutAskingMeForPermission = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NeverSendAnErrorReportToMicrosoftAboutMicrosoftDynamics365 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoPreferenceForSendingAnErrorReportToMicrosoftAboutMicrosoftDynamics365 = 0,
	}
	
	/// <summary>
	/// Samesite mode for Session Cookie: 0 is Default, 1 is None, 2 is Lax , 3 is Strict
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_SameSiteModeForSessionCookie
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Default = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lax = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Strict = 3,
	}
	
	/// <summary>
	/// Scheduling engine for Appointments and Service Activities
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_SchedulingEngine
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LegacySchedulingEngine = 0,
	}
	
	/// <summary>
	/// SharePoint Deployment Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_SharePointDeploymentType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Online = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OnPremises = 1,
	}
	
	/// <summary>
	/// Indicates the status of opt-in or opt-out operations for dynamics 365 azure sync.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_SyncOptInSelectionStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Passed = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Processing = 1,
	}
	
	/// <summary>
	/// Validation mode for apps in this environment
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_ValidationMode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Block = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Off = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Warn = 1,
	}
	
	/// <summary>
	/// Yammer Post Method
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Organization_YammerPostMethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Private = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Public = 0,
	}
	
	/// <summary>
	/// Power Pages Languages
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PowerPageLanguages
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Arabic = 1025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BasqueBasque = 1069,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulgarianBulgaria = 1026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CatalanCatalan = 1027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChineseChina = 2052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChineseHongKongSar = 3076,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChineseTraditional = 1028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CroatianCroatia = 1050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CzechCzechRepublic = 1029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DanishDenmark = 1030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DutchNetherlands = 1043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		English = 1033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EstonianEstonia = 1061,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FinnishFinland = 1035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FrenchFrance = 1036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GalicianSpain = 1110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GermanGermany = 1031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GreekGreece = 1032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Hebrew = 1037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HindiIndia = 1081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HungarianHungary = 1038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IndonesianIndonesia = 1057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ItalianItaly = 1040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JapaneseJapan = 1041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KazakhKazakhstan = 1087,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KoreanKorea = 1042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LatvianLatvia = 1062,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LithuanianLithuania = 1063,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MalayMalaysia = 1086,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NorwegianBokmLNorway = 1044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PolishPoland = 1045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PortugueseBrazil = 1046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PortuguesePortugal = 2070,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RomanianRomania = 1048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RussianRussia = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SerbianCyrillicSerbia = 3098,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SerbianLatinSerbia = 2074,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SlovakSlovakia = 1051,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SlovenianSlovenia = 1060,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SpanishTraditionalSortSpain = 3082,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SwedishSweden = 1053,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThaiThailand = 1054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TurkishTRkiye = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UkrainianUkraine = 1058,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		VietnameseVietnam = 1066,
	}
	
	/// <summary>
	/// The type of Purchase Process for this lead.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PurchaseProcess
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Committee = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Individual = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unknown = 2,
	}
	
	/// <summary>
	/// The timeframe that this lead is likely to make a purchase in.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PurchaseTimeFrame
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Immediate = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NextQuarter = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisQuarter = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThisYear = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unknown = 4,
	}
	
	/// <summary>
	/// Identifies if a plug-in should be executed from a parent pipeline, a child pipeline, or both.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SdkMessageProcessingStep_InvocationSource
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Child = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Internal = -1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Parent = 0,
	}
	
	/// <summary>
	/// Run-time mode of execution, for example, synchronous or asynchronous.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SdkMessageProcessingStep_Mode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Asynchronous = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Synchronous = 0,
	}
	
	/// <summary>
	/// Stage in the execution pipeline that the SDK message processing step is in.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SdkMessageProcessingStep_Stage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FinalPostOperationForInternalUseOnly = 55,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InitialPreOperationForInternalUseOnly = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalPostOperationAfterExternalPluginsForInternalUseOnly = 45,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalPostOperationBeforeExternalPluginsForInternalUseOnly = 35,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalPreOperationAfterExternalPluginsForInternalUseOnly = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalPreOperationBeforeExternalPluginsForInternalUseOnly = 15,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MainOperationForInternalUseOnly = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostCommitStageFiredAfterTransactionCommitForInternalUseOnly = 90,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostOperation = 40,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostOperationDeprecated = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PreCommitStageFiredBeforeTransactionCommitForInternalUseOnly = 80,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PreOperation = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PreValidation = 10,
	}
	
	/// <summary>
	/// Status of the SDK message processing step.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SdkMessageProcessingStep_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disabled = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enabled = 0,
	}
	
	/// <summary>
	/// Reason for the status of the SDK message processing step.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SdkMessageProcessingStep_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disabled = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enabled = 1,
	}
	
	/// <summary>
	/// Deployment that the SDK message processing step should be executed on; server, client, or both.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SdkMessageProcessingStep_SupportedDeployment
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Both = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftDynamics365ClientForOutlookOnly = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServerOnly = 0,
	}
	
	/// <summary>
	/// Type of user.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_AccessMode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Administrative = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DelegatedAdmin = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonInteractive = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Read = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReadWrite = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SupportUser = 3,
	}
	
	/// <summary>
	/// Type of address for address 1, such as billing, shipping, or primary address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_Address1_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Method of shipment for address 1.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_Address1_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Type of address for address 2, such as billing, shipping, or primary address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_Address2_AddressTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Method of shipment for address 2.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_Address2_ShippingMethodCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Azure state of user.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_AzureState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Exists = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotFoundOrHardDeleted = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SoftDeleted = 1,
	}
	
	/// <summary>
	/// License type of user. This is used only in the on-premises version of the product. Online licenses are managed through Microsoft 365 Office Portal.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_CalType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Administrative = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Basic = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeviceBasic = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeviceEnterprise = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeviceEssential = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DeviceProfessional = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enterprise = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Essential = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldService = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Professional = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProjectService = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sales = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Service = 10,
	}
	
	/// <summary>
	/// User delete state.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_DeletedState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotDeleted = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SoftDeleted = 1,
	}
	
	/// <summary>
	/// Indicates the approval options for server-side synchronization or Email Router access.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_EmailRouterAccessApproval
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approved = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Empty = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PendingApproval = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rejected = 3,
	}
	
	/// <summary>
	/// Incoming email delivery method for the user.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_IncomingEmailDeliveryMethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ForwardMailbox = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftDynamics365ForOutlook = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServerSideSynchronizationOrEmailRouter = 2,
	}
	
	/// <summary>
	/// User invitation status.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_InviteStatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvitationAccepted = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvitationExpired = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvitationNearExpired = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvitationNotSent = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvitationRejected = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvitationRevoked = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invited = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_Msdyn_AgentType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApplicationUser = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BotApplicationUser = 192350001,
	}
	
	/// <summary>
	/// Indicates the type of bot
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_Msdyn_BotProvider
	{
		
		/// <summary>
		/// Indicates that the user is not a bot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 192350002,
		
		/// <summary>
		/// Other type of bot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 192350001,
		
		/// <summary>
		/// CCI first party Bot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		VirtualAgent = 192350000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_Msdyn_UserType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BotUser = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CrmUser = 192350000,
	}
	
	/// <summary>
	/// Outgoing email delivery method for the user.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_OutgoingEmailDeliveryMethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftDynamics365ForOutlook = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServerSideSynchronizationOrEmailRouter = 2,
	}
	
	/// <summary>
	/// Preferred address for the user.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_PreferredAddressCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MailingAddress = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OtherAddress = 2,
	}
	
	/// <summary>
	/// Preferred email address for the user.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_PreferredEmailCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Preferred phone number for the user.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SystemUser_PreferredPhoneCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HomePhone = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MainPhone = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MobilePhone = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OtherPhone = 2,
	}
	
	/// <summary>
	/// Information about team membership type.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Team_MembershipType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Guests = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Members = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MembersAndGuests = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Owners = 2,
	}
	
	/// <summary>
	/// Information about team type.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Team_TeamType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Access = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OfficeGroup = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Owner = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SecurityGroup = 2,
	}
	
	/// <summary>
	/// Options for Template Default View
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum TemplateDefaultView
	{
		
		/// <summary>
		/// Grid View
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GridView = 2,
		
		/// <summary>
		/// List View
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ListView = 3,
		
		/// <summary>
		/// Tiles View
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TilesView = 1,
	}
}
#pragma warning restore CS1591
